### ISSUE TITLE
Scope updating to version 3.0.0-alpha with Janus API

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#107]
@san983 please scope what needs to be done as a reference for next sprint's work on creating version 3.0.0-alpha. This includes:

(@agonza1 and @san983 editing _here_) ⬇️ 

### New events?
_No, by now there is no new event definition, so nothing new to declare in the SDK v3.x_

### New config vars?
- 'connectionId': undefined,
- 'username': undefined, (SIP username)
- 'authuser': undefined, (SIP authentication username)
- 'secret': undefined, (SIP secret)
- 'server': undefined, (SIP server/registrar)
- 'customer': undefined, (Voxbone customer header)
- rtcSession: {connection : {localStreams : [], remoteStreams : []}},

### New methods for building & sending the REGISTER?
  * Direct Authentication (sending credentials from front-end to Janus and to Kamailio directly) 
_besides the new/updated config vars (related to previous bullet)_
`setupInboundCalling` now need `details` & `callback`

  * Advanced Authentication (connectionId tokenisation mechanism) 
_-> KONG! @san983 to define_

### Add new error definitions / codes
_TBD_

**Comment by san983** [comment]
* Add new error definitions / codes
