### ISSUE TITLE
Encapsulate Voxbone.js - allow multiple instances

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/webrtc-js#110]
Define a constructor for the library so the anyone implementing it should use

i.e. `var voxbone = New Voxbone({config})` 

Check https://github.com/voxbone-workshop/webrtc-js/issues/90 for more info

**Comment by agonza1** [comment]
While it is encapsulated it still can't load different instances and the approach being followed wasn't very efficient. Moving to try a different approach where we doesn't load all the voxbone.js dependencies each time we instantiate a `Voxbone`
