### ISSUE TITLE
Update callstats.js to v3.21.x

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/webrtc-js#111]
### v3.21.x
- https://groups.google.com/forum/#!topic/callstats-dev/VC13wY93csk

### v3.20.x
- https://groups.google.com/forum/#!topic/callstats-dev/zXzspxl6EXY

⚠️ Check method deprecations!

**Comment by chadwallacehart** [comment]
@agonza1 should be the lead on this.

**Comment by agonza1** [comment]
commit: https://github.com/voxbone-workshop/webrtc-js/commit/32acfc84fc961ed181c3b9ad4d88e7d0a3e9882a (testing)
