### ISSUE TITLE
Implement CallStats custom error handler

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/webrtc-js#12]
CallStats marks any call that does not connect due to a cause in the SIP network. Most of these causes are because the user cancelled the call, the SIP caller didn't pick up, or because the SIP caller was busy.

Today in CallStats these errors show as _Failures_ with a cause of _UnknownError_

I would like to distinguish between calls that failed due to some issue in the network/WebRTC vs. those that are normal user experiences.

Nitesh has experimented with using CallStats's custom Error handler to pass more detailed error information.

Nitesh recommends using his previous implementation as a guide: https://webrtc.voxbone.com/webrtc_test/voxbone-0.0.6_callstats.js

Details on jsSIP's error information can be found here: http://jssip.net/documentation/2.0.x/api/causes/

We should be able to pass this error code,cause and other information to CallStats to refine our error reporting so that we can better focus on real issues.

**Comment by san983** [comment]
Copying email from Binoy (from CallStats)

```
We are doing beta testing of web sockets, could you test this and let us know if you have any issues? It would be a great help if you can test this in your environment. 

Here is the link to our JS. https://api.callstats.io/static/callstats-ws.min.js
```

We might try to add this in a 2.1.1 release on first week of October

cc @chadwallacehart

**Comment by san983** [comment]
https://github.com/voxbone-workshop/webrtc-js/issues/41
