### ISSUE TITLE
Set projects click2call buttons pointing to click2vox beta

### ISSUE THREAD

**Issue by agonza1** [voxbone-workshop/webrtc-js#131]
- [x] voxbone.ai
- [x] voxrec.me
- [x] viber.voxbone.com
- [x] voxbone.video
- [x] click2vox.com
- [x] portal WebRTC
- [x] voxconf.me
- [x] sip2webr.tc
- [ ] ~did2webr.tc~

**Comment by san983** [comment]
@fikrifirat @chadwallacehart New voxbone.com site doesn't use our widget to place a call to Voxbone itself. Should we ask for it?
