### ISSUE TITLE
Send WebRTC call ratings daily

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#132]
There's a python script that queries Kibana for WebRTC logs for `rating` load type and sends weekly reports to customers. Can you update it to send daily reports?

**Comment by san983** [comment]
@agonza1 already pushed the change for this. Please check it @fikrifirat.

For reference, it's a cron job in this [droplet](https://cloud.digitalocean.com/droplets/31330264/graphs?i=98f99d) -> 178.62.247.217
