### ISSUE TITLE
Replicate FireFox 46 getUserMedia error

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/webrtc-js#19]
FF 46 on Windows 10 got stuck on getUserMedia for me. See if this issue can be replicated. If yes, address it.

![image](https://cloud.githubusercontent.com/assets/6531125/16958867/5daf936a-4db0-11e6-9086-dba3e5435e1f.png)

**Comment by san983** [comment]
@emilianop11, since you are Windows 10 and FireFox user. Have you been experiencing something like this lately?

**Comment by emilianop11** [comment]
@san983 Im getting the same messages but it didnt got stuck, actually I never had problems. Now I tried several times and it seems to be working OK despite those warnings.

**Comment by san983** [comment]
Ok, let's keep it here in `icebox` just for reference
