### ISSUE TITLE
Call fails to cancel when clicked `End Call` when in RINGING state

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#36]
> We can hangup at 3 different moment: 
> - The destination phone isn't ringing yet. Works fine. 
> - The destination phone is picked up. Works fine as well. 
> - The destination phone is ringing.
> 
> If we hang up from the web page while the destination phone is ringing, the webpage assume the call is ended but the destination phone is still ringing. 
> If we pick up the destination phone at this moment we'll have a blank line and if we aren't taking the call, the blank call is going on the voicemail(long message with nothing).

When tested, this line is printed to the console only in the failing scenario : 
`reportError: Missing dom error parameter                                   voxbone-2.1.js:33960`

![image](https://cloud.githubusercontent.com/assets/3737677/20439143/f5129de8-adc2-11e6-8306-abaef2f00cd2.png)

Looks like linked to callstats.io

**Comment by san983** [comment]
This is related to https://github.com/versatica/JsSIP/commit/99e1f4d8aadd46e75fa248a22e2dbecf90e1fdca

**Comment by fikrifirat** [comment]
@san983  Tested it, now CANCEL message is sent to the correct session and the call terminates correctly while in RINGING state.
