### ISSUE TITLE
[EPAUTH] Add a redirect service to use either Voxbone's or Click2vox.io backup 

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/webrtc-js#40]
- [x] Create a redirect service

- [x] Point to that new URL in voxbone.js (and release a patch)

- [x] Document the process in the Wiki on how to switch endpoints

**Comment by agonza1** [comment]
I will make a PR with the updated URLs for the EPAUTH and you can find here the documentation: https://github.com/voxbone-workshop/epauth/wiki/Epauth-environments,-credentials-and-failover#for-redirecting-epauth-voxbone-to-the-backup-epauth (also available in master wiki)
