### ISSUE TITLE
Add X-UserToUser Header

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/webrtc-js#57]
RingRing is requesting that we allow X-UserToUser to pass from the client JS through our network.

Customer:
>With WebRTC, we can add X-Voxbone-Context to the SIP header but we cannot add another header like user-to-user or X-usertouser. When checking https://developers.voxbone.com/docs/webrtc/overview/ it seems there is no limitation for the header (The format is ‘header_name’: ‘header_value’.)

Torrey:
>Our network white-lists headers for reasons of security.  That's why the X-Voxbone-Context header was implemented to provide a safe end-to-end messaging channel.
>It should be rather straight forward for them to set up a sip proxy to extract data encoded in X-Voxbone-Context and insert it into X-UserToUser

Customer:
>Can you please allow X-UserToUser through WebRTC ?
>We are not able today to extract the X-Voxbone-Context and add it to a different header.
>This is a routing from our SBC to another network.

**Comment by chadwallacehart** [comment]
Question to @tsearle:
>FYI on what RingRing had to say about extracting from X-Voxbone-Context and creating their own X-UserToUser header. I am not so sure it is trivial in most cases to ask customers to setup a proxy or to do header manipulation in their SBC. 

>Is whitelisting X-UserToUser a security concern? What would it take to whitelabel this header?Would that need to be done in the WebRTC Gateway and/or our ingress SBC?

**Comment by chadwallacehart** [comment]
The customer was able to resolve this:

>We have found how to change the header in our SBC.
>I’ve also updated the ticket.
--
>Thank you, I’ve tested and we received the UUI correctly on our PRA.
>I will now made some change in production to validate it with the customer.

@fikrifirat - please close this once you have updated our documentation & FAQ.

**Comment by fikrifirat** [comment]
Updated documentation:

https://developers.voxbone.com/docs/webrtc/overview/

Extra Headers & Context
The VoxboneJS comes with two extra Voxbone SIP headers. Use this option to manually pick the Voxbone POP if you are targeting a specific geolocation or to define context. Voxbone The extraHeader param is in the form of a javascript object. The format is ‘header_name’: ‘header_value’.

Voxbone headers that can be set:
var headers = {
    'X-Voxbone-Pop': 'value',
    'X-Voxbone-Context': 'value'
}

Alternatively, context can also be set through the ‘context’ object within the SDK. It should be set before calling init or basicAuthInit functions.
