### ISSUE TITLE
Fix wording on rating rating stars

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#60]
onhover, 1 star reads `Excellent` while 5 stars reads `Unacceptable`, it should be in the reverse order.

I couldn't add the screenshot because as I press keys the hover message disappears.

**Comment by san983** [comment]
Issue moved to [voxbone-workshop/click2vox-com #578](https://github.com/voxbone-workshop/click2vox-com/issues/578) via [**ZenHub**](https://www.zenhub.com/)
