### ISSUE TITLE
Make customers access call ratings

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#61]
Currently we allow the option to enable/disable `Ask for rating after the call ends` but don't give them access to those ratings on their widgets. This may be also important for Portal Widget customers to review these on a per DID basis. 

Customers are interested in having an API access to these ratings, a reasonable assumption would be ratings per DID for portal widget customers and ratings per SIP URI for click2vox customers. 

Portal widget customers should have priority.

Customers asked for this so far:
`CSC Telecom Ltd`

Initial proposal for the endpoint:

Request body:
```
{
  "WebRTCUsername":"username",
  "WebRTCPassword":"password",
  "E164":"+1234567890",
  "SIPuri":"1234@sip.customer.com",
  "FromDate":"2017-01-01 00:00:00",
  "ToDate":"2017-01-31 23:59:59"
}
```

@san983 please comment for example response with what we can get from callstats related to this request

**Comment by chadwallacehart** [comment]
@fikrifirat - do we need an API for this? That would be some work to develop and maintain?
Can we just send them a periodic snapshot of their ratings instead? @agonza1 could help write a script to extract this information from kibana and write it to file. Perhaps we could also use that script to email the file.

**Comment by fikrifirat** [comment]
@chadwallacehart that would also work for the time being. @agonza1 let's discuss this one today.

But in general, I think this should be a feature available by default, otherwise it's not a feature at all as we use it only internally.

**Comment by san983** [comment]
@agonza1 let's talk about this tomorrow, checking a log example at Kibana and see if all the needed info is there

**Comment by fikrifirat** [comment]
Customer is OK to have a periodic email/dump on these, rather than consuming it via the API. They prefer XML formatting.

@agonza1 @chadwallacehart

**Comment by chadwallacehart** [comment]
@san983 @agonza1 - please add this one to your sprint

**Comment by chadwallacehart** [comment]
long ago we had a `rating` field as part of the webrtc logs that get sent to kibana. This no longer appears to be there. It look like ratings are saved for click2vox.com in the MongoDB, but that is a problem for the portal widget generator. Please confirm the behavior and investigate the log posting behavior as part of this issue (or a sister issue)

**Comment by san983** [comment]
@agonza1 so, the set of tasks would be

- [ ] Check how `voxbone.js` (currently v2.1.5) are sending the logs to Voxbone. Check at Kibana that, both _Click2vox_ and _Portal Widget Generator_ widgets. 

- [ ] Investigate how to create a script to parse the ratings for a user

- [ ] Create a script to deliver the ratings to a user

**Comment by agonza1** [comment]
`ratings.py` script that sends (after user confirmation):
1- For click2vox, all the ratings to the users that had ratings the last week
2- For Portal Widget, it sends ratings to all the customers in the `voxbone_workshop` Analyticcs DB in the `accounts_ratings` table (again if they have ratings).

For changing the default origin email we have the python script send_email.py where we can change the origin and the text message. All the rating files and scripts are in /home/analytics-admin/scripts/ratings

**Comment by san983** [comment]
@agonza1 quick thing, I think we should version those scripts. What about moving them here to this repo? Thoughts?

**Comment by agonza1** [comment]
Ok @san983  sounds good, they are python scripts though. May be I could add them to the wiki or to the Analytics repo? I also could add them as a script in here but I feel this scripts are too different for this repo

**Comment by san983** [comment]
@agonza1 you're right, by "this repo" I meant the "Analytics" repo.

**Comment by agonza1** [comment]
Here we have the scripts for this issue: https://github.com/voxbone-workshop/Analytics/tree/master/ratings
