### ISSUE TITLE
One-way media on Firefox

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#62]
User media is not available to the called end on Firefox, only incoming.

I tested on Firefox 51.0.1 (64-bit) on MAC Sierra, a customer also reported this issue.

Update : _**On beta it works fine : 52.0b3 (64-bit)**_
JS Warnings:
```
WebRTC interfaces with the “moz” prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.  voxbone-2.1.min.js:20:14065
TURNS is not yet supported. voxbone-2.1.min.js:20
onaddstream is deprecated! Use peerConnection.ontrack instead.  voxbone-2.1.min.js:20
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia  voxbone-2.1.min.js:20:7115
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.  voxbone-2.1.min.js:20:17817
```

Console logs:
[one-way-media-FF51.txt](https://github.com/voxbone-workshop/webrtc-js/files/757275/one-way-media-FF51.txt)

**Comment by san983** [comment]
Hi @fikrifirat we just tried it and it working OK for me and for @emilianop11 too.

We both tried with latest FF stable 51.0.1 on OSX and Windows.

Regarding the warnings we have to check them deeply.

**Comment by fikrifirat** [comment]
Customer confirmed it was also working properly for them. The current console logs are exactly the same as before. Looks like an unidentified intermittent issue. Closing this one

**Comment by san983** [comment]
Keeping this one in order to gather more info about this (or replicate it)

**Comment by san983** [comment]
Closing this since it was not happening lately
