### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by fikrifirat** [voxbone-workshop/webrtc-js#88]
Doesn't prevent any behaviour but puts a huge error log in the developer console.

Examples : http://newcomvoip.com/ , https://cleverideas.com.mx/

Also happens time to time on https://www.weblook.com/ when i refresh

**Comment by san983** [comment]
Short term solution:
Try/catch  the error.

Long / Real solution:
Use our widget in our own scope.

**Comment by san983** [comment]
Reference: http://requirejs.org/docs/errors.html#mismatch

**Comment by san983** [comment]
Seems that forcing `cli2ck2vox.js` script load `async` does the trick. Some old widgets are not using it, we might contact the users to upgrade/fix it. We're checking who shoud be contacted here

https://docs.google.com/spreadsheets/d/1z1_5ql6pWRGrY8DxMIXA-6Bwh5bl3J3GQ3hLQ2O1Nr0/edit#gid=0

**Comment by san983** [comment]
Tested & Fixed at `blog.voxbone.com`

@fikrifirat we need to contact all the clients that don't have the `async` tag in the script loading to have it.

**Comment by san983** [comment]
We'll keep this ticket in order to track the clients that have to be contacted. A better JS solutions will be delivered when we'll probably have to change many aspects of the code snippet on removing jssip
