### ISSUE TITLE
[2017-03-21] Callstats.io v3.18.0 release breaks voxbone.js

### ISSUE THREAD

**Issue by agonza1** [voxbone-workshop/webrtc-js#91]
Today 3/21/2017 callstats updated to v3.18 and it broke voxbone.js. It didn't allow us to place calls through WebRTC. Error thrown:

![image](https://cloud.githubusercontent.com/assets/16296681/24166189/7d0a2ec2-0e40-11e7-8203-d2d2f388a7e9.png)

Solution: Released [v2.2.2](https://github.com/voxbone-workshop/webrtc-js/releases/tag/v2.2.2)  fixing callstats version to v3.17.10.

Callstats update link:https://groups.google.com/forum/#!topic/callstats-dev/1cbmjQ3T1xU

**Comment by chadwallacehart** [comment]
Should we be locking ourselves to a specific callstats.io version and only incrementing that after testing?

**Comment by san983** [comment]
@chadwallacehart That's exactly the new approach https://github.com/voxbone-workshop/webrtc-js/pull/92/files#diff-afff0c5356ff47417f4556519585606aR2369
