### ISSUE TITLE
CSV Daily Report extracting logs from kibana

### ISSUE THREAD

**Issue by agonza1** [voxbone-workshop/webrtc-js#95]
Daily cron job that:
Imports from Kivana Techrrific logs -> Converts to CSV -> Send email with csv attached to Techrrific 

### Default fields to provide:
“customer_remote_pktloss_pct”
“answerCodecs”
“customer_local_jitter_avg”
“carrier_remote_pktloss_pct”
“carrier_local_jitter_avg”
“customer_local_pktloss_pct”
“browser_ip”
“carrier_local_pktloss_pct”
“customer_remote_jitter_avg”
"carrier_remote_jitter_avg”
"customer_rtt_avg”
“uuid”
“carrier_rtt_avg”
“channel”
“server”

**Comment by san983** [comment]
Hi @agonza1, what is the status of this? should we move it to Done/Closed?

**Comment by agonza1** [comment]
It's complete. We are currently sending those reports 👍
