### ISSUE TITLE
Chrome 60: `ERR_INSECURE_RESPONSE` on  WebSocket interface

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/webrtc-js#99]
Chrome versions 60 (currently Dev) appears to have an issue with the certificate used on Voxbone's Websocket server. This prevents calls from being made on Chrome

![image](https://cloud.githubusercontent.com/assets/6531125/25610213/574eb056-2ef0-11e7-9d52-76918b78f415.png)

@san983 please work with @ggenot to make sure this is addressed.

**Comment by san983** [comment]
It seems that it is an issue related to the wildcard certificate `*.voxout.voxbone.com`. @ggenot is about to check it and replace it for a new one

**Comment by san983** [comment]
We need to setup a maintenance window for this update. https://voxbonecorp.slack.com/archives/G2GHQUQ2E/p1493733254501079

**Comment by san983** [comment]
https://voxbonecorp.slack.com/archives/G2GHQUQ2E/p1493792601226601

@ggenot said:
```
Need to be discussed with NOC but not before next week I guess, as we have a security warning we will be able to use "emergency maintenace"

We tried to buy a new certificate yesterday but had some issue with the credit card, we will see with finance dep. today
```

Targeting on Monday?

**Comment by san983** [comment]
```
Geoffroi Genot [9:37 AM] 
I switched the certificate for be.voxout.voxbone.com is there someone that can test now on your side ? (I'm still waiting validation of the NOC)

Chad Hart [9:38 AM] 
confirmed I no longer get the Certificate Error issue in Chrome
```

I verified that too. Closing and thanks @ggenot
